require:
  - rubocop-rspec

AllCops:
  Include:
    - '**/Capfile'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/config.ru'
    - '**/app/**/*'
    - '**/bin/**/*'
    - '**/config/**/*'
    - '**/db/**/*'
    - '**/lib/**/*'
    - '**/spec/**/*'
  Exclude:
    - '**/*.coffee'
    - '**/*.conf'
    - '**/*.css'
    - '**/*.gif'
    - '**/*.erb'
    - '**/*.ico'
    - '**/*.html'
    - '**/*.jpeg'
    - '**/*.jpg'
    - '**/*.js'
    - '**/*.jst.ejs'
    - '**/*.png'
    - '**/*.log'
    - '**/*.scss*'
    - '**/*.sql'
    - '**/*.sqlite3'
    - '**/*.txt'
    - '**/*.yml'
    - '**/app/assets/**/*'
    - '**/coverage/**/*'
    - '**/db/schema.rb'
    - '**/log/**/*'
    - '**/public/**/*'
    - '**/tmp/**/*'
  RunRailsCops: true
Lint/HandleExceptions:
  Exclude:
    - 'config/unicorn.rb'
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*devise_create_admin_users.rb'
Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Style/Documentation:
  Enabled: false
Style/CollectionMethods:
  # Mapping from undesired method to desired_method
  # e.g. to use `detect` over `find`:
  #
  # CollectionMethods:
  #   PreferredMethods:
  #     find: detect
  PreferredMethods:
    map: 'collect'
    map!: 'collect!'
    reduce: 'inject'
    detect: 'find'
    select: 'find_all'
